(define (deriv expe var)
  (cond ((number? expe) 0)
        ((variable? expe)
         (if (same-variable? expe var) 1 0)
         )
        ((sum? expe)
         (make-sum (deriv (addend expe) var)
                   (deriv (augend expe) var)
                   )
         )
        ((product? expe)
         (make-sum (make-product (multiplier expe)
                                 (deriv (multiplicand expe) var)
                                 )
                   (make-product (deriv (multiplier expe) var)
                                 (multiplicand expe)
                                 )
                   )
         )
        ((exponentation? expe)
         (make-product (make-product (exponent expe) (make-exponentiation (base expe) (- (exponent expe) 1))) (deriv (base expe) var))
         )
        (else (
               error "unkown exp"
               ))
        )
  )
(define (variable? x) (symbol? x))
(define (same-variable? a b)
  (and (variable? a) (variable? b) (eq? a b))
  )
(define (make-sum a b) (list '+ a b))
(define (make-product a b) (list '* a b))
(define (sum? x)
  (and (pair? x) (eq? (car x) '+))
  )
(define (addend s) (cadr s))
(define (augend s) (caddr s))
(define (product? x)
  (and (pair? x) (eq? (car x) '*))
  )
(define (multiplier p) (cadr p))
(define (multiplicand p) (caddr p))
(define (make-exponentiation base exponent)
  (list '** base exponent)
  )
(define (base ex) (cadr ex))
(define (exponent ex) (caddr ex))
(define (exponentation? ex)
  (and (pair? ex) (eq? (car x) '**))
  )
