(load "ex1.21.scm")
(define (timed-prime-test n)
  (newline)
  (display "start:")
  (display n)
  (start-prime-test n (runtime))
  )
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time) n)
      (start-prime-test (search-next n) start-time)
    )
  )
(define (report-prime elapsed-time n)
  (display " end:")
  (display n)
  (display " *** ")
  (display elapsed-time)
  )
(define (search-next n)
  (if (= 0 (remainder n 2))
    (+ n 1)
    (+ n 2)
    )
  )

(timed-prime-test 1000)
(timed-prime-test 10000)
(timed-prime-test 100000)
