(define (make-mobile left right)
  (list left right)
  )
(define (make-branch length structure)
  (list length structure)
  )

(define (left-branch tree)
  (car tree)
  )
(define (right-branch tree)
  (cadr tree)
  )
(define (branch-lenght b)
  (car b)
  )
(define (branch-structure b)
  (cadr b)
  )

(define (total-weight tree)
  (+ (branch-weight (left-branch tree))
     (branch-weight (right-branch tree))
     )
  )
(define (branch-weight b)
  (if (pair? (branch-structure b))
    (total-weight (branch-structure b))
    (branch-structure b)
    )
  )

