(define (cube x) (* x x x))
(define (improve y x)
  (/ (+ (/ x (* y y)) (* 2 y)
        ) 3))
(define (cube-iter guess x)
  (if (good-enough? guess x)
      guess
    (cube-iter (improve guess x)
               x)))
(define (good-enough? guess x)
  (< (abs (- (cube guess) x)) 0.001)
  )
(define (cuberoot x) (cube-iter 1.0 x))

(cuberoot 8.0)
(cuberoot 27.0)
